const SaleTempController = require("../controller/SaleTempController");
const { isAuthen, isStaff } = require("../middleware/auth");

module.exports = function registerLegacyCartRoutes(app) {
  app.post(
    "/api/saleTemp/printBillAfterPay",
    isAuthen,
    isStaff,
    SaleTempController.printBillAfterPay,
  );
  app.post(
    "/api/saleTemp/endSale",
    isAuthen,
    isStaff,
    SaleTempController.endSale,
  );
  app.post(
    "/api/saleTemp/submitToKitchen",
    isAuthen,
    isStaff,
    SaleTempController.submitToKitchen,
  );
  app.get(
    "/api/saleTemp/pendingCounterOrders",
    isAuthen,
    isStaff,
    SaleTempController.pendingCounterOrders,
  );
  app.post(
    "/api/saleTemp/printBillBeforePay",
    isAuthen,
    isStaff,
    SaleTempController.printBillBeforePay,
  );
  app.delete(
    "/api/saleTemp/removeSaleTempDetailModal",
    isAuthen,
    isStaff,
    SaleTempController.removeSaleTempDetailModal,
  );
  app.post(
    "/api/saleTemp/createSaleTempDetail",
    isAuthen,
    isStaff,
    SaleTempController.createSaleTempDetail,
  );
  app.put(
    "/api/saleTemp/selectSize",
    isAuthen,
    isStaff,
    SaleTempController.selectSize,
  );
  app.put(
    "/api/saleTemp/unSelectTaste",
    isAuthen,
    isStaff,
    SaleTempController.unSelectTaste,
  );
  app.put(
    "/api/saleTemp/selectTaste",
    isAuthen,
    isStaff,
    SaleTempController.selectTaste,
  );
  app.get("/api/saleTemp/info/:id", isAuthen, isStaff, SaleTempController.info);
  app.post(
    "/api/saleTemp/generateSaleTempDetail",
    isAuthen,
    isStaff,
    SaleTempController.generateSaleTempDetail,
  );
  app.put(
    "/api/saleTemp/updateQty",
    isAuthen,
    isStaff,
    SaleTempController.updateQty,
  );
  app.delete(
    "/api/saleTemp/removeAll",
    isAuthen,
    isStaff,
    SaleTempController.removeAll,
  );
  app.delete(
    "/api/saleTemp/remove/:id",
    isAuthen,
    isStaff,
    SaleTempController.remove,
  );
  app.get("/api/saleTemp/list/", isAuthen, isStaff, SaleTempController.list);
  app.post(
    "/api/saleTemp/create",
    isAuthen,
    isStaff,
    SaleTempController.create,
  );
};
